spring.application.name=ecommerce-api
spring.datasource.url=jdbc:postgresql://localhost:5432//ecommercedb
spring.datasource.password=santiago123
spring.datasource.username=santiago
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret="secret"
jwt.expiration=900000
