spring.application.name=ecommerce-api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
spring.datasource.password=santiago123
spring.datasource.username=santiago
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret="K11qc3QqIZWKljZJnd9AScRqnIrweu2KXUEpxER8kw/Kymh2814JwOxyEMYkHsPs1LbBfEZyzRbWl9iBY6DW3A=="
jwt.expiration=900000
app.rabbitmq.exchange=order-exchange
app.rabbitmq.queue=order-queue
app.rabbitmq.routing-key=order.*
app.rabbitmq.routing-key-order-created=order.created