@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzYW50aWFnb0B0ZXN0LmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc4ODgzMDkxNywiZXhwIjoxNzg4ODMxODE3fQ.0WQox4rYRg3fg29y9r4L7VL0PkgbdZUis2Pru_XfnLPcIHvw_0TmllBOMaf99O8RIgU96E85homirWyzIS_iIw


### AUTH

### 1. Register user
### Creates User + Cart
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "userName": "santiago",
  "email": "admin@mail.com",
  "password": "password123"
}


### 2. Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "santiago@test.com",
  "password": "password123"
}


### PRODUCTS

### 3. Get all products
GET {{baseUrl}}/products
Authorization: Bearer {{token}}
Accept: application/json


### 4. Get a specific product
GET {{baseUrl}}/products/1
Authorization: Bearer {{token}}
Accept: application/json


### CART

### 5. Get my cart
GET {{baseUrl}}/cart
Authorization: Bearer {{token}}
Accept: application/json


### 6. Add Laptop x2
POST {{baseUrl}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}


### 7. Add Mouse x3
POST {{baseUrl}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 2,
  "quantity": 3
}


### 8. Get cart details
GET {{baseUrl}}/cart
Authorization: Bearer {{token}}
Accept: application/json


### 9. Update CartItem quantity
### Note: Update the ID below to match the actual CartItem ID
PATCH {{baseUrl}}/cart/items/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "quantity": 1
}


### 10. Remove a CartItem
### Note: Update the ID below to match the actual CartItem ID
DELETE {{baseUrl}}/cart/items/1
Authorization: Bearer {{token}}


### 11. Clear cart
DELETE {{baseUrl}}/cart
Authorization: Bearer {{token}}


### CHECKOUT

### 12. Successful checkout
### No cartId is required
POST {{baseUrl}}/checkout
Authorization: Bearer {{token}}
Accept: application/json


### 13. Attempt checkout again
### Expected to fail because the cart is now empty
POST {{baseUrl}}/checkout
Authorization: Bearer {{token}}
Accept: application/json


### ORDERS

### 14. Get my orders
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}
Accept: application/json


### 15. Add out-of-stock product
POST {{baseUrl}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 5,
  "quantity": 1
}


### 16. Checkout with out-of-stock product
### Expected to fail
POST {{baseUrl}}/checkout
Authorization: Bearer {{token}}
Accept: application/json


### 17. Verify the product remains in the cart
GET {{baseUrl}}/cart
Authorization: Bearer {{token}}
Accept: application/json


### 18. Verify no new order was created
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}
Accept: application/json